AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  repoName:
    Type: String
    Description: Name of an existing ECR Repository
Resources:
  StelligentEcrRepo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref repoName
Outputs:
  ECRRepo:
    Description: 'ECR Repo'
    Value: !Ref StelligentEcrRepo