AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  repo_name:
    Type: String
    Description: Name of an existing ECR Repository
Resources:
  StelligentEcrRepo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref repo_name
Outputs:
  ECR Repo:
    Description: 'ECR Repo'
    Value: !Ref StelligentEcrRepo